asr:
    threads: 500
    blockSize: 5120
    baidu: http://audiotest.baidu.com/open_asr_test
    local: https://localhost:8000/asr
    json: https://localhost:8000/json

nlu:
    version: 1.0
    protocol: cellphone
    url: http://ai.ecarx.com.cn/test/ai/