asr:
    threads: 500
    timeout: 30000
    url: http://audiotest.baidu.com/open_asr_test

nlu:
    version: 1.0
    timeout: 30000
    protocol: cellphone
    url: http://ai.ecarx.com.cn/test/ai/



