server:
    port: 8000
    http2:
        enabled: true
    compression:
        enabled: true
    ssl:
        key-store: classpath:asr.jks
        key-password: EcarxAsr
        key-store-password: EcarxAsr

spring:
    profiles:
        active: dev

