server:
    port: 8000
asr:
    threads: 500
    blockSize: 5120

    upUrl: http://audiotest.baidu.com/open_asr_test/up
    downUrl: http://audiotest.baidu.com/open_asr_test/down

nlu:
    version: 1.0
    protocol: cellphone
    url: "http://ai.ecarx.com.cn/test/ai/"



